# Generated by Django 3.2.5 on 2021-07-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=35)),
                ('lastName', models.CharField(max_length=55)),
                ('userName', models.CharField(max_length=40)),
                ('passWord', models.CharField(max_length=86)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('likes', models.IntegerField()),
                ('disLikes', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('userId', models.IntegerField(editable=False)),
                ('likes', models.IntegerField()),
                ('disLikes', models.IntegerField()),
                ('upperComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
    ]
